version: 2

references:
  base: &base
    macos:
      xcode: "9.4.0"
    environment:
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      XCODE_PATH: /Applications/Xcode-9.4.app
      FASTLANE_SKIP_UPDATE_CHECK: 1

  steps:
    restore_carthage_cache: &restore_carthage_cache
      restore_cache:
        key: 1-carthage-{{ checksum "Cartfile.resolved" }}

    save_carthage_cache: &save_carthage_cache
      save_cache:
        key: 1-carthage-{{ checksum "Cartfile.resolved" }}
        paths:
          - Carthage

    restore_bundler_cache: &restore_bundler_cache
      restore_cache:
        key: 1-bundler-{{ checksum "Gemfile.lock" }}

    save_bundler_cache: &save_bundler_cache
      save_cache:
        key: 1-bundler-{{ checksum "Gemfile.lock" }}
        paths:
          - Vendor/bundler

    store_build_artifacts: &store_build_artifacts
      store_artifacts:
        path: build
        destination: build

    store_gym_logs: &store_gym_logs
      store_artifacts:
        path: ~/Library/Logs/gym
        destination: logs/gym

    bundle_install: &bundle_install
      run: bundle install --path Vendor/bundler

    attach_build_workspace: &attach_build_workspace
      attach_workspace:
        at: build

jobs:
  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml

  danger:
    docker:
      - image: dantoml/danger:latest
    steps:
      - checkout
      - run: danger

  tests:
    <<: *base
    steps:
      - checkout
      - <<: *restore_carthage_cache
      - run: .circleci/bootstrap-carthage.sh
      - <<: *save_carthage_cache
      - <<: *restore_bundler_cache
      - <<: *bundle_install
      - <<: *save_bundler_cache
      - run: bundle exec fastlane set_build_number
      - run: bundle exec fastlane tests
      - run: bundle exec fastlane send_coveralls
      - store_test_results:
          path: fastlane/test_output
      - store_artifacts:
          path: fastlane/test_output
          destination: test_output
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: logs/scan

  screenshots:
    <<: *base
    steps:
      - checkout
      - <<: *restore_carthage_cache
      - run: .circleci/bootstrap-carthage.sh
      - <<: *save_carthage_cache
      - <<: *restore_bundler_cache
      - <<: *bundle_install
      - <<: *save_bundler_cache
      - run: bundle exec fastlane set_build_number
      - run: 'bundle exec fastlane screenshots | egrep -v $UI_TEST_CIRCLE_TOKEN'
      - persist_to_workspace:
          root: fastlane
          paths:
            - screenshots
      - store_artifacts:
          path: fastlane/screenshots
          destination: screenshots
      - store_artifacts:
          path: ~/Library/Logs/snapshot
          destination: logs/snapshot

  beta_build:
    <<: *base
    steps:
      - checkout
      - <<: *restore_carthage_cache
      - run: .circleci/bootstrap-carthage.sh
      - <<: *save_carthage_cache
      - <<: *restore_bundler_cache
      - <<: *bundle_install
      - <<: *save_bundler_cache
      - run: bundle exec fastlane beta_match
      - run: bundle exec fastlane set_build_number
      - run: bundle exec fastlane beta_build
      - <<: *store_build_artifacts
      - <<: *store_gym_logs
      - persist_to_workspace:
          root: build
          paths:
            - adhoc

  beta_upload:
    <<: *base
    steps:
      - checkout
      - <<: *attach_build_workspace
      - <<: *restore_bundler_cache
      - <<: *bundle_install
      - <<: *save_bundler_cache
      - run: bundle exec fastlane beta_match
      - run: bundle exec fastlane beta_upload

  release_build:
    <<: *base
    steps:
      - checkout
      - <<: *restore_carthage_cache
      - run: .circleci/bootstrap-carthage.sh
      - <<: *save_carthage_cache
      - <<: *restore_bundler_cache
      - <<: *bundle_install
      - <<: *save_bundler_cache
      - run: bundle exec fastlane release_match
      - run: bundle exec fastlane set_build_number
      - run: bundle exec fastlane release_build
      - <<: *store_build_artifacts
      - <<: *store_gym_logs
      - persist_to_workspace:
          root: build
          paths:
            - release

  release_upload:
    <<: *base
    steps:
      - checkout
      - <<: *attach_build_workspace
      - <<: *restore_bundler_cache
      - <<: *bundle_install
      - <<: *save_bundler_cache
      - run: bundle exec fastlane release_match
      - run: bundle exec fastlane release_upload

  release_metadata:
    <<: *base
    steps:
      - checkout
      - <<: *restore_bundler_cache
      - <<: *bundle_install
      - <<: *save_bundler_cache
      - run: bundle exec fastlane release_metadata

  release_screenshots:
    <<: *base
    steps:
      - checkout
      - <<: *restore_bundler_cache
      - <<: *bundle_install
      - <<: *save_bundler_cache
      - run: bundle exec fastlane release_screenshots

workflows:
  version: 2
  app:
    jobs:
      - swiftlint:
          filters:
            branches:
              ignore: [screenshots, metadata]

      - danger:
          filters:
            branches:
              ignore: [screenshots, metadata]

      - tests:
          requires:
            - swiftlint
            - danger
          filters:
            branches:
              ignore: [screenshots, metadata]

      - screenshots:
          filters:
            branches:
              only: new-screenshots

      - beta_build:
          requires:
            - tests
          filters:
            branches:
              only: [develop]

      - beta_upload:
          requires:
            - beta_build

      - release_build:
          requires:
            - tests
          filters:
            branches:
              only: [master]

      - release_upload:
          requires:
            - release_build
          filters:
            branches:
              ignore: metadata

      - release_metadata:
          filters:
            branches:
              only: [master, metadata]

      - release_screenshots:
          filters:
            branches:
              only: screenshots
