# vim: set ft=ruby:

fastlane_version "1.48.0"

default_platform :ios

APP_NAME = 'CI2Go'

def set_build_number
  increment_build_number(build_number: ENV['CIRCLE_BUILD_NUM'])
end

def build_ipa(export_method = 'app-store', scheme = 'CI2Go')
  unlock_keychain
  gym(
    scheme: scheme,
    # export_method: export_method,
    codesigning_identity: ENV['DEVELOPER_NAME'],
    use_legacy_build_api: true,
    configuration: 'Release',
    clean: false,
    output_directory: "Build/#{export_method}",
    archive_path: "Build/#{export_method}/#{scheme}.xcarchive"
  )
end

def import_certificate_from_base64(file_spec, b64str, password = nil)
  require 'tempfile'
  require 'base64'
  f = Tempfile.open(file_spec)
  f.write(Base64.decode64(b64str))
  f.close
  import_certificate(
    certificate_path: f.path,
    certificate_password: password
  )
end

platform :ios do

  desc 'Build AdHoc version ipa'
  lane :build_adhoc do
    set_build_number
    build_ipa('ad-hoc')
  end

  desc 'Build Distribution version ipa'
  lane :build_distribution do
    set_build_number
    build_ipa
  end

  desc 'Import certs'
  lane :import_certs do
    create_keychain(
      default_keychain: !!ENV['CI'],
      unlock: true
    )
    import_certificate_from_base64(
      ['apple_developer_authority', '.cer'],
      ENV['APPLE_AUTHORITY_BASE64'],
    )
    import_certificate_from_base64(
      ['distribution-cert', '.cer'],
      ENV['DISTRIBUTION_CERTIFICATE_BASE64'],
    )
    import_certificate_from_base64(
      ['distribution-key', '.p12'],
      ENV['DISTRIBUTION_KEY_BASE64'],
      ENV['DISTRIBUTION_CERT_PASSWORD']
    )
    sh 'security list-keychains'
    sh 'security find-identity'
  end

  desc 'Runs all the tests'
  lane :test do
    scan(
      workspace: "./#{APP_NAME}.xcworkspace",
      scheme: APP_NAME,
      skip_slack: true,
      device: 'iPhone 6s'
    )
    snapshot(
      workspace: "./#{APP_NAME}.xcworkspace",
      scheme: APP_NAME
    )
  end

  desc 'Deploy a new version to S3'
  lane :deploy_s3 do
    path = "#{ENV['CIRCLE_PROJECT_USERNAME']}/#{ENV['CIRCLE_PROJECT_REPONAME']}/#{ENV['CIRCLE_BUILD_NUM']}/"
    s3(
      ipa: "Build/ad-hoc/#{APP_NAME}.ipa",
      dsym: "Build/ad-hoc/#{APP_NAME}.app.dSYM.zip",
      bucket: ENV['S3_BUCKET'],
      path: path,
      html_file_name: "#{path}index.html",
      html_template_path: './fastlane/templates/index.html.erb',
      plist_template_path: './fastlane/templates/app.plist.erb'
    )
    url = lane_context[SharedValues::S3_HTML_OUTPUT_PATH]
    branch = ENV['CIRCLE_BRANCH']
    if branch
      slack(
        message: "#{APP_NAME} version: #{get_version_number}(#{ENV['CIRCLE_BUILD_NUM']}) from `#{branch}` is available! #{url}",
        success: true,
        default_payloads: [:lane]
      )
    end
  end

  desc 'Submit a new Beta Build to Apple TestFlight'
  lane :deploy_testflight do
    testflight(skip_submission: true)
  end
end
