# vim: set ft=ruby:

fastlane_version "1.48.0"

default_platform :ios

APP_NAME = 'CI2Go'

def import_certificate_from_base64(file_spec, b64str, password = nil)
  require 'tempfile'
  require 'base64'
  f = Tempfile.open(file_spec)
  f.write(Base64.decode64(b64str))
  f.close
  import_certificate(
    certificate_path: f.path,
    certificate_password: password
  )
end

platform :ios do

  desc 'Build AdHoc version ipa'
  lane :build do
    increment_build_number build_number: ENV['CIRCLE_BUILD_NUM']
    unlock_keychain
    gym(
      scheme: APP_NAME,
      codesigning_identity: ENV['DEVELOPER_NAME'],
      use_legacy_build_api: true,
      configuration: 'Release',
      clean: false,
      output_directory: "Build",
      archive_path: "Build/#{APP_NAME}.xcarchive"
    )
  end

  desc 'Import certs'
  lane :import_certs do
    create_keychain(
      default_keychain: !!ENV['CI'],
      unlock: true
    )
    import_certificate_from_base64(
      ['apple_developer_authority', '.cer'],
      ENV['APPLE_AUTHORITY_BASE64'],
    )
    import_certificate_from_base64(
      ['distribution-cert', '.cer'],
      ENV['DISTRIBUTION_CERTIFICATE_BASE64'],
    )
    import_certificate_from_base64(
      ['distribution-key', '.p12'],
      ENV['DISTRIBUTION_KEY_BASE64'],
      ENV['DISTRIBUTION_CERT_PASSWORD']
    )
    sh 'security list-keychains'
    sh 'security find-identity'
  end

  desc 'Runs all the tests'
  lane :test do
    scan(
      workspace: "./#{APP_NAME}.xcworkspace",
      scheme: APP_NAME,
      skip_slack: true,
      device: 'iPhone 6s'
    )
    snapshot(
      workspace: "./#{APP_NAME}.xcworkspace",
      scheme: APP_NAME
    )
  end

  desc 'Deploy a new version to S3'
  lane :deploy_s3 do
    ipa = "Build/#{APP_NAME}.ipa"
    resign(
      ipa: ipa,
      signing_identity: ENV['DEVELOPER_NAME'],
      provisioning_profile: {
        'com.ci2go.ios.Circle' => './fastlane/profiles/AdHoc_com.ci2go.ios.Circle.mobileprovision',
        'com.ci2go.ios.Circle.watchkitapp' => './fastlane/profiles/AdHoc_com.ci2go.ios.Circle.watchkitapp.mobileprovision',
        'com.ci2go.ios.Circle.watchkitapp.ext' => './fastlane/profiles/AdHoc_com.ci2go.ios.Circle.watchkitapp.ext.mobileprovision'
      }
    )
    path = "#{ENV['CIRCLE_PROJECT_USERNAME']}/#{ENV['CIRCLE_PROJECT_REPONAME']}/#{ENV['CIRCLE_BUILD_NUM']}/"
    s3(
      ipa: ipa,
      dsym: "Build/#{APP_NAME}.app.dSYM.zip",
      bucket: ENV['S3_BUCKET'],
      path: path,
      html_file_name: "#{path}index.html",
      html_template_path: './fastlane/templates/index.html.erb',
      plist_template_path: './fastlane/templates/app.plist.erb'
    )
    url = lane_context[SharedValues::S3_HTML_OUTPUT_PATH]
    branch = ENV['CIRCLE_BRANCH']
    if branch
      slack(
        message: "#{APP_NAME} version: #{get_version_number}(#{ENV['CIRCLE_BUILD_NUM']}) from `#{branch}` is available! #{url}",
        success: true,
        default_payloads: [:lane]
      )
    end
  end

  desc 'Submit a new Beta Build to Apple TestFlight'
  lane :deploy_testflight do
    ipa = "Build/#{APP_NAME}.ipa"
    resign(
      ipa: ipa,
      signing_identity: ENV['DEVELOPER_NAME'],
      provisioning_profile: {
        'com.ci2go.ios.Circle' => './fastlane/profiles/AppStore_com.ci2go.ios.Circle.mobileprovision',
        'com.ci2go.ios.Circle.watchkitapp' => './fastlane/profiles/AppStore_com.ci2go.ios.Circle.watchkitapp.mobileprovision',
        'com.ci2go.ios.Circle.watchkitapp.ext' => './fastlane/profiles/AppStore_com.ci2go.ios.Circle.watchkitapp.ext.mobileprovision'
      }
    )
    testflight(skip_submission: true)
  end
end
