devices([
  "iPhone 8",
  "iPhone 8 Plus",
  # "iPhone 11",
  "iPhone 11 Pro",
  "iPhone 11 Pro Max",
  "iPhone SE (2nd generation)",
  "iPad Pro (9.7-inch)",
  "iPad (7th generation)",
  "iPad Pro (11-inch) (2nd generation)",
  "iPad Pro (12.9-inch) (4th generation)",
  # "iPad Air (3rd generation)"
])

languages(["en-US"])

# clear_previous_screenshots(true)

project "CI2Go.xcodeproj"
scheme "CI2GoUITests"
launch_arguments ["-circleToken #{ENV.fetch('UI_TEST_CIRCLE_TOKEN')}"]

# For more information about all available options run
# fastlane action snapshot
derived_data_path 'DerivedData'
namespace_log_files false
# ttest_without_building true
erase_simulator true
