devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
  "iPad Retina",
  "iPad Pro"
])

languages([
  "en-US"
])

# launch_arguments("-favColor red")

scheme "CI2Go"
output_directory "./fastlane/screenshots"

project "./CI2Go.xcodeproj"
workspace "./CI2Go.xcworkspace"
