devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone X",
  "iPad Pro (12.9-inch)",
  "iPad Pro (10.5-inch)",
  "iPad Pro (9.7-inch)"
#   "Apple TV 1080p"
])

languages(["en-US"])

# clear_previous_screenshots(true)

project "CI2Go.xcodeproj"
scheme "CI2GoUITests"
launch_arguments ["-circleToken #{ENV.fetch('UI_TEST_CIRCLE_TOKEN')}"]

# For more information about all available options run
# fastlane action snapshot
derived_data_path 'DerivedData'
namespace_log_files true
# ttest_without_building true
